FEATURE_SEMANTICS = {
    "sttl": "Source TTL value — reveals the operating system and device type of the sender. Unusual TTL values are a strong indicator of spoofed traffic or non-standard devices.",
    "ct_state_ttl": "Compound feature combining TTL value and connection state — the model's most reliable binary detection signal. Abnormal combinations indicate scanning or spoofing.",
    "dload": "Destination load in bits per second — the primary DoS flood signal. Values orders of magnitude above baseline indicate the destination is being flooded.",
    "dbytes": "Total bytes sent toward the destination — asymmetric exchange where the destination receives far more than the source sent indicates payload delivery, typical of exploit traffic.",
    "synack": "Time between SYN and SYN-ACK packets — anomalous timing indicates SYN flood attacks or covert channel communication.",
    "ackdat": "Time between SYN-ACK and final ACK — together with synack forms the full TCP handshake RTT. Manipulation indicates evasion.",
    "tcprtt": "Total TCP round-trip time — the sum of synack and ackdat. Extreme values indicate network manipulation or geographic anomalies.",
    "proto": "Network protocol (TCP/UDP/ICMP) — protocol misuse is a common attack technique, e.g. ICMP tunneling or UDP floods.",
    "service": "Application-layer service identified at the destination port — unexpected services on unusual ports indicate port scanning or service exploitation.",
    "state": "TCP connection termination state (FIN/RST/INT/CON) — high RST counts indicate rejected connections typical of port scanning.",
    "dur": "Flow duration in seconds — very short high-volume flows indicate flooding; unusually long low-volume flows indicate slow exfiltration or C2 beaconing.",
    "sbytes": "Total bytes sent from source — combined with dbytes reveals data transfer asymmetry.",
    "spkts": "Packet count from source — high counts with small bytes indicate packet flooding.",
    "dpkts": "Packet count from destination — response packet volume relative to request volume reveals server behavior.",
    "sport": "Source port — ephemeral port patterns can identify automated tools and scanners.",
    "dsport": "Destination port — targeted port reveals the intended service and attack type.",
    "sload": "Source bits per second — combined with dload reveals which direction the flood is coming from.",
    "sjit": "Source jitter — variance in inter-packet timing. Regular jitter indicates automated tools; irregular jitter indicates evasion.",
    "djit": "Destination jitter — variance in response timing. High jitter under attack indicates server stress.",
    "sintpkt": "Mean inter-packet time from source in milliseconds — very low values indicate flooding; regular precise values indicate automated attack tools.",
    "dintpkt": "Mean inter-packet time from destination — response rate reveals server capacity and stress.",
    "dttl": "Destination TTL — response TTL reveals the destination OS type and can detect TTL manipulation in responses.",
    "dwin": "Destination TCP window size — manipulation of window size is used in TCP-based evasion and slow attacks.",
    "stcpb": "Source TCP base sequence number — predictable sequence numbers indicate vulnerable implementations; random patterns are normal.",
    "dtcpb": "Destination TCP base sequence number — same as stcpb for the response direction.",
    "trans_depth": "HTTP transaction depth — deep pipelined HTTP requests can indicate web application attack probing.",
    "res_bdy_len": "HTTP response body length — unusually large responses can indicate data exfiltration; unusually small can indicate error exploitation.",
    "is_sm_ips_ports": "Flag: source and destination IP and port are the same — this is highly anomalous and indicates loopback abuse or reflexive attack traffic.",
    "ct_flw_http_mthd": "Count of HTTP methods in this flow — multiple different HTTP methods in one flow indicates web application fuzzing or enumeration.",
    "is_ftp_login": "FTP login flag — authenticated FTP sessions that show attack patterns indicate credential theft or FTP exploitation.",
    "ct_ftp_cmd": "FTP command count — unusually high command counts indicate automated FTP exploitation or brute force.",
    "ct_srv_src": "Count of connections to the same service from this source in the last 100 flows — high counts indicate service-targeted scanning or flooding from one source.",
    "ct_srv_dst": "Count of connections to the same service toward this destination in the last 100 flows — high counts indicate this destination service is being targeted.",
    "ct_dst_ltm": "Count of connections to this destination in the last 100 flows — measures how much attention this destination is receiving recently.",
    "ct_src_ltm": "Count of connections from this source in the last 100 flows — high counts identify prolific sources, typical of scanners and bots.",
    "ct_src_dport_ltm": "Count of connections from this source to this destination port in the last 100 flows — targeted repeated connection attempts indicate brute force or exploitation.",
    "ct_dst_sport_ltm": "Count of connections to this destination from this source port in the last 100 flows — unusual port persistence indicates C2 or tunneling.",
    "ct_dst_src_ltm": "Count of connections between this exact source-destination pair in the last 100 flows — high counts indicate persistent targeted communication, typical of C2 or exfiltration.",
}

ATTACK_SIGNATURES = {
    "DoS": "Volumetric flood attack — attacker overwhelms the destination with traffic to deny service to legitimate users.",
    "Exploits": "Vulnerability exploitation — attacker sends crafted payloads to trigger a known software vulnerability and gain unauthorized access or code execution.",
    "Reconnaissance": "Network scanning and probing — attacker systematically scans hosts and ports to map the network and identify targets.",
    "Generic": "Generic attack pattern — traffic matches known attack signatures that do not fit a specific category.",
    "Backdoors": "Backdoor communication — covert channel between compromised host and attacker, typically for persistent access or command and control.",
    "Fuzzers": "Protocol fuzzing — attacker sends malformed or random inputs to find crashes and vulnerabilities in network services.",
    "Shellcode": "Shellcode injection — binary attack payload designed to execute arbitrary commands on the target system.",
    "Analysis": "Traffic analysis and enumeration — attacker uses packet-level probing to enumerate services, versions, and configurations.",
    "Worms": "Self-propagating worm — malicious traffic from a host that has been compromised and is now scanning and infecting other hosts autonomously.",
}
